"""Artifact Builder — Generates, tests, and hashes a buildable artifact.

Runs AFTER Stripe confirms payment. Not before.
"""
import hashlib
import json
import os
import subprocess
import tempfile
import time
import zipfile
from pathlib import Path
from typing import Dict, List, Optional


class ArtifactBuilder:
    """Builds a real artifact after payment is confirmed."""

    def __init__(self, workspace: str = None):
        self.workspace = workspace or os.path.expanduser("~/.membra/builds")
        os.makedirs(self.workspace, exist_ok=True)

    def build(self, job_id: str, spec: Dict) -> Dict:
        """Build artifact based on job specification.

        Returns build result with artifact path, hash, test results.
        """
        build_dir = os.path.join(self.workspace, job_id)
        os.makedirs(build_dir, exist_ok=True)

        # Generate artifact based on spec
        artifact_type = spec.get("type", "python_script")
        artifact_content = self._generate_artifact(artifact_type, spec)

        # Write artifact to file
        filename = spec.get("filename", "artifact.py")
        artifact_path = os.path.join(build_dir, filename)
        with open(artifact_path, "w") as f:
            f.write(artifact_content)

        # Compute hash
        content_hash = hashlib.sha256(artifact_content.encode()).hexdigest()

        # Run tests
        test_result = self._run_tests(build_dir, filename, spec.get("tests", []))

        return {
            "job_id": job_id,
            "artifact_path": artifact_path,
            "artifact_type": artifact_type,
            "filename": filename,
            "content_hash": content_hash,
            "size_bytes": len(artifact_content.encode()),
            "test_result": test_result,
            "built_at": time.time(),
            "status": "built" if test_result.get("passed") else "test_failed",
        }

    def _generate_artifact(self, artifact_type: str, spec: Dict) -> str:
        """Generate artifact content based on type and spec."""
        if artifact_type == "python_script":
            return self._generate_python_script(spec)
        elif artifact_type == "solana_contract":
            return self._generate_solana_contract(spec)
        elif artifact_type == "rust_module":
            return self._generate_rust_module(spec)
        else:
            return spec.get("code", "# Default artifact\n")

    def _generate_python_script(self, spec: Dict) -> str:
        """Generate a Python script artifact."""
        description = spec.get("description", "A generated Python utility")
        function_name = spec.get("function_name", "main")
        return f'''#!/usr/bin/env python3
"""
{description}
Generated by MEMBRA AI Artifact Builder
Job ID: {spec.get("job_id", "unknown")}
Built at: {time.strftime("%Y-%m-%d %H:%M:%S")}
"""

def {function_name}(*args, **kwargs):
    """Main function."""
    print(f"Running {function_name} with args: {{args}}, kwargs: {{kwargs}}")
    return {{"status": "ok", "args": args, "kwargs": kwargs}}

if __name__ == "__main__":
    result = {function_name}()
    print(json.dumps(result, indent=2))
'''

    def _generate_solana_contract(self, spec: Dict) -> str:
        return '''use anchor_lang::prelude::*;

#[program]
pub mod membra_generated {
    use super::*;

    pub fn initialize(ctx: Context<Initialize>) -> Result<()> {
        msg!("MEMBRA generated contract initialized");
        Ok(())
    }
}

#[derive(Accounts)]
pub struct Initialize {}
'''

    def _generate_rust_module(self, spec: Dict) -> str:
        return '''pub fn membra_generated_function() -> String {
    "Hello from MEMBRA".to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generated() {
        assert_eq!(membra_generated_function(), "Hello from MEMBRA");
    }
}
'''

    def _run_tests(self, build_dir: str, filename: str, test_commands: List[str]) -> Dict:
        """Run tests on the artifact."""
        if not test_commands:
            # Default: try to run the file with Python
            test_commands = ["python3", filename]

        try:
            result = subprocess.run(
                test_commands,
                cwd=build_dir,
                capture_output=True,
                text=True,
                timeout=30,
            )
            return {
                "passed": result.returncode == 0,
                "exit_code": result.returncode,
                "stdout": result.stdout[:2000],
                "stderr": result.stderr[:1000],
                "command": " ".join(test_commands),
            }
        except Exception as e:
            return {
                "passed": False,
                "error": str(e),
                "command": " ".join(test_commands),
            }

    def generate_report_zip(self, build_result: Dict, payment: Dict) -> str:
        """Generate a downloadable ZIP report for the buyer.

        Contains:
        - The artifact file
        - Build/test log
        - Payment receipt
        - Hash proofs
        """
        job_id = build_result["job_id"]
        zip_path = os.path.join(self.workspace, f"{job_id}_report.zip")

        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
            # Artifact
            artifact_path = build_result["artifact_path"]
            zf.write(artifact_path, os.path.basename(artifact_path))

            # Build report
            report = {
                "job_id": job_id,
                "artifact_type": build_result["artifact_type"],
                "content_hash": build_result["content_hash"],
                "test_result": build_result["test_result"],
                "built_at": build_result["built_at"],
                "payment": {
                    "session_id": payment.get("session_id", ""),
                    "amount_usd": payment.get("amount_usd", 0),
                    "verified_at": payment.get("verified_at", ""),
                    "receipt_url": payment.get("receipt_url", ""),
                },
            }
            report_json = json.dumps(report, indent=2, default=str)
            zf.writestr("build_report.json", report_json)

            # README
            readme = f"""MEMBRA AI Artifact Build Report
================================
Job ID: {job_id}
Artifact Type: {build_result['artifact_type']}
Content Hash: {build_result['content_hash']}
Test Status: {'PASS' if build_result['test_result'].get('passed') else 'FAIL'}

Payment
-------
Amount: ${payment.get('amount_usd', 0):.2f} USD
Stripe Session: {payment.get('session_id', 'N/A')}
Verified: {payment.get('verified_at', 'N/A')}

Files
-----
- {os.path.basename(artifact_path)}: The generated artifact
- build_report.json: Full build metadata
- README.txt: This file

This artifact was generated and tested after Stripe confirmed payment.
"""
            zf.writestr("README.txt", readme)

        return zip_path
